apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: refresher
  name: refresher
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: refresher
  name: refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: refresher
subjects:
- kind: ServiceAccount
  name: refresher
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: refresher
  name: refresher
  namespace: default
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: refresher-config
  namespace: default
data:
  refresher.conf: |
    config-api=http://config-api:8080/config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: refresher
  name: refresher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: refresher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: refresher
    spec:
      serviceAccountName: refresher
      containers:
      - image: ghcr.io/jakeloxton/refresher:main
        name: refresher
        env:
          - name: PRODUCTION_LOGGING
            value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /etc/refresher/
      volumes:
      - name: config
        configMap:
          name: refresher-config
